attendanceProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dashboard.views import FirstPageView
from dashboard.views import CheckEmail, fetch_processing_image
from accounts.views import upload_file

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', FirstPageView.as_view(), name='FirstPage'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('validate/', CheckEmail),
    path('upload_file/<str:username>/', upload_file),
    path('processing_image/<str:param>/', fetch_processing_image),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from .views import DashboardView, MarkAttendanceView, TrainingView, MarkAttendanceOutView, AttendanceListView,\
    AllAttendanceView

app_name = 'dashboard'

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='home'),
    path('markattendance/', MarkAttendanceView.as_view(), name='mark-attendance'),
    path('markoutattendance/', MarkAttendanceOutView.as_view(), name='mark-out-attendance'),
    path('training/all/', TrainingView.as_view(), name="training"),
    path('attendance/<str:username>/', AttendanceListView.as_view(), name="attendance-history"),
    path('attendance/show/all/', AllAttendanceView.as_view(), name="all-attendance-history"),
]

dashboard/models.py
from django.db import models
from accounts.models import Accounts


# Create your models here.

class Attendance(models.Model):
    userid = models.ForeignKey(Accounts, on_delete=models.CASCADE)
    marked_at = models.DateTimeField(blank=True, null=True)
    marked_out = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'attendance'

dashboard/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from django.views import View
from django.http import HttpResponse, JsonResponse, response
from utils.recognize import Recognizer
from utils.training import Training
from accounts.models import Accounts
from .models import Attendance
from django.views.decorators.http import require_http_methods
from django.shortcuts import get_object_or_404
from django.conf import settings
import os
import pathlib
from datetime import datetime, timedelta, timezone

NOW = datetime.now()
START_DATE = datetime(NOW.year, NOW.month, NOW.day, hour=00, minute=00, second=00)
END_DATE = datetime(NOW.year, NOW.month, NOW.day, hour=23, minute=59, second=59)


# Create your views here.
@require_http_methods(["GET", "POST"])
def fetch_processing_image(request, param):
    if param in request.session:
        return JsonResponse({
            param: request.session[param]
        }, status=200)

    return HttpResponse("fail")


def check_session(request):
    if 'username' in request.session and 'typ' in request.session and 'name' in request.session:
        context_data = dict()
        context_data['username'], context_data['typ'], context_data['name'] = request.session['username'], \
                                                                              request.session['typ'], request.session[
                                                                              'name']
        if request.session['typ'] == 'Admin':
            context_data['permission'] = True
        return context_data
    return False


@require_http_methods(["POST"])
def CheckEmail(request):
    if request.POST.get('email'):
        user_obj = Accounts.objects.filter(email=request.POST['email'])
        if user_obj:
            return JsonResponse({
                'username': user_obj[0].username,
                'status': 200
            }, status=200)
        else:
            return JsonResponse({
                'msg': "Email does not exist in our records",
                'status': 400
            }, status=200)
    else:
        return JsonResponse({
            'msg': "Email does not exist in our records",
            'status': 400
        }, status=200)


class MarkAttendanceOutView(View):

    def get(self, request):
        res = Recognizer(status='out')
        if res.get('status') == 11:
            user = Accounts.objects.filter(username=res['username'])
            not_marked = Attendance.objects.filter(userid_id=user[0].id, marked_at__gte=START_DATE, marked_at__lte=END_DATE, marked_out__isnull=True)
            if not_marked:
                not_marked[0].marked_out = NOW
                not_marked[0].save()
                res['msg'] = "Attendance has been marked out successfully for " + res['username']
            elif Attendance.objects.filter(userid_id=user[0].id, marked_out__gte=START_DATE, marked_out__lte=END_DATE):
                res['msg'] = "Attendance has already been marked out successfully for " + res['username']
                return JsonResponse(res, status=200)
            else:
                res['msg'] = res['username'] + " need to mark in first."
        return JsonResponse(res, status=200)


class TrainingView(View):
    template_name = "dashboard/training.html"

    def get(self, request):
        context_data = check_session(request)
        if context_data:
            if context_data.get('permission'):
                return render(request, template_name=self.template_name, context=context_data)
            else:
                return render(request, template_name='403.html')
        else:
            return redirect('accounts:login')

    def post(self, request):
        res = Training()
        if res.get('status') == 11:
            res['msg'] = "Image processing compelete"
            return JsonResponse(res, status=200)
        elif res.get('status') == 00:
            res['msg'] = "500 internal server error"
            return JsonResponse(res, status=200)


class MarkAttendanceView(View):
    def get(self, request):
        res = Recognizer(status='in')
        if res.get('status') == 11:
            user = Accounts.objects.filter(username=res['username'], active=1)
            if not user:
                res['msg'] = "sorry that users does not exist."
                return JsonResponse(res, status=200)

            if Attendance.objects.filter(userid_id=user[0].id, marked_at__gte=START_DATE, marked_at__lte=END_DATE):
                res['msg'] = "Attendance has already been marked successfully for " + res['username']
                return JsonResponse(res, status=200)

            attd = Attendance.objects.create(userid=user[0], marked_at=NOW)
            attd.save()
            res['msg'] = "Attendance has been marked successfully for " + res['username']
        return JsonResponse(res, status=200)


class FirstPageView(View):
    template_name = "dashboard/first_page.html"

    def get(self, request):
        context_data = check_session(request)
        if not context_data:
            return render(request, self.template_name, {})
        else:
            return redirect('dashboard:home')


class AllAttendanceView(View):
    template_name = "dashboard/all_attendance.html"

    def get(self, request):
        context_data = check_session(request)
        if context_data.get('permission'):
            final_obj = {}
            all_usr_obj = Accounts.objects.all()
            context_data['total_user'] = all_usr_obj.count()
            all_name_join = {_.name: [_.created_at.date(), []] for _ in all_usr_obj}
            all_diff = {k: NOW.date() - v[0] for k, v in all_name_join.items()}
            [all_name_join[_.userid.name][1].append([_.created_at.date(), _.marked_at, _.marked_out]) for _ in Attendance.objects.all() ]

            for k, v in all_name_join.items():

                final_obj[k] = {}
                for _ in range(all_diff[k].days):
                    day = v[0] + timedelta(_)
                    final_obj[k][_] = {}
                    final_obj[k][_]['day'] = day
                    final_obj[k][_]['marked_at'] = "-"
                    final_obj[k][_]['marked_out'] = "-"
                    final_obj[k][_]['status'] = 'Absent'

                    for idx in v[1]:
                        if day == idx[0]:
                            final_obj[k][_]['day'] = day
                            final_obj[k][_]['marked_at'] = idx[1]
                            final_obj[k][_]['marked_out'] = idx[2]
                            final_obj[k][_]['status'] = 'Present'

            context_data['final_obj'] = final_obj
            return render(request, template_name=self.template_name, context=context_data)
        return render(request, template_name='403.html')


class AttendanceListView(View):
    template_name = "dashboard/attendance.html"

    def get(self, request, username):
        context_data = check_session(request)
        user_obj = get_object_or_404(Accounts, username=username)

        if context_data.get('permission'):
            att_obj = Attendance.objects.filter(userid=user_obj.id)
        elif context_data['username'] == username:
            att_obj = Attendance.objects.filter(userid=user_obj.id)
        else:
            return render(request, template_name='403.html')

        present_data = {_.marked_at.date(): [_.marked_at, _.marked_out] for _ in att_obj}

        if not context_data:
            return redirect('accounts:login')
        context_data['profile_username'] = user_obj.name
        context_data['joined_on'] = user_obj.created_at
        diff = NOW.date() - user_obj.created_at.date()
        context_data['total_attendance'] = diff.days
        context_data['total_present'] = len(att_obj)
        context_data['total_absent'] = diff.days - len(att_obj)
        context_data['att_obj'] = att_obj
        context_data['full_name'] = user_obj.name
        atte_dict = {}

        for _ in range(diff.days):
            atte_dict[_] = {}
            day = user_obj.created_at.date() + timedelta(_)
            atte_dict[_]['day'] = day
            atte_dict[_]['marked_at'] = "-"
            atte_dict[_]['marked_out'] = "-"
            atte_dict[_]['status'] = 'Absent'

            if present_data.get(day):
                atte_dict[_]['day'] = day
                atte_dict[_]['marked_at'] = present_data[day][0]
                atte_dict[_]['marked_out'] = present_data[day][1]
                atte_dict[_]['status'] = 'Present'

        context_data['atte_obj'] = atte_dict
        context_data['name'] = user_obj.name

        return render(request, self.template_name, context_data)


class DashboardView(View):
    template_name = "dashboard/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get(self, request):
        context_data = check_session(request)
        if context_data:
            context_data['userid'] = Accounts.objects.get(username=context_data['username'])
            return render(request, self.template_name, context_data)
        else:
            return redirect('accounts:login')

dashboard/templates/dashboard/all_attendance.html
{% extends "main.html" %}
{% load static %}
{% block content %}
        <div class="container mt-5">
    <div class="row">
        <div class="col col-md-3 p-3">
            <div class="card bg-primary text-light shadow" style="width: auto;">
                <div class="card-body">
                    <h5 class="card-title">Total Users</h5>
                    <h6 class="card-subtitle ">
                        <h1 class="">{{ total_user }}</h1>
                    </h6>
                </div>
            </div>
        </div>
    <div>

        <div class="container">
    <div class="d-flex mt-4">
        <h3 class="fs-3 text-capitalize lead">Attendance List of All Users</h3>
    </div>
    <hr>
    <div class="row my-4 card shadow">
        <div class="col card-body">
            <table class="table table-striped" id="AttendanceListingTable">
                <thead>
                    <tr>
                        <th scope="col">Day</th>
                        <th scope="col">Name</th>
                        <th scope="col">Marked In</th>
                        <th scope="col">Marked Out</th>
                        <th scope="col">Status</th>
                    </tr>
                </thead>
                <tbody>

                    {% for k,v in final_obj.items %}
                    {% for obj in v.values %}
                     <tr>
                        <th scope="row">{{ obj.day }}</th>
                        <td>{{ k }}</td>
                        <td><b>{{ obj.marked_at }}</b></td>
                        <td><b>{{ obj.marked_out }}</b></td>
                        <td class="lead">{{ obj.status }}</td>
                    </tr>
                    {% endfor %}
                    {% empty %}
                    <tr class="mt-5">
                        <td colspan="7" align="center">
                            <p>No Attendance found</p>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <hr>
        </div>
    </div>
</div>


{% endblock %}


{% block scripts %}
<script>
        $(document).ready(function() {
                $('#AttendanceListingTable').DataTable();
        });
</script>
{% endblock %}

dashboard/templates/dashboard/attendance.html
{% extends "main.html" %}
{% load static %}
{% block content %}
        <div class="container mt-5">
    <div class="row">
        <div class="col col-md-3 p-3">
            <div class="card bg-primary text-light shadow" style="width: auto;">
                <div class="card-body">
                    <h5 class="card-title">Day Joined</h5>
                    <h6 class="card-subtitle ">
                        <h1 class="">{{ joined_on|date:"d F Y" }}</h1>
                    </h6>
                </div>
            </div>
        </div>
        <div class="col col-md-3 p-3">
            <div class="card bg-primary text-light shadow" style="width: auto;">
                <div class="card-body">
                    <h5 class="card-title">Total Attendance</h5>
                    <h6 class="card-subtitle ">
                        <h1 class="">{{ total_attendance }}</h1>
                    </h6>
                </div>
            </div>
        </div>
        <div class="col col-md-3 p-3">
            <div class="card bg-primary text-light shadow" style="width: auto;">
                <div class="card-body">
                    <h5 class="card-title">Total Present</h5>
                    <h6 class="card-subtitle ">
                        <h1 class="">{{ total_present }}</h1>
                    </h6>
                </div>
            </div>
        </div>
        <div class="col col-md-3 p-3">
            <div class="card  bg-primary text-light shadow" style="width: auto;">
                <div class="card-body">
                    <h5 class="card-title">Total Absent</h5>
                    <h6 class="card-subtitle">
                        <h1 class="">{{ total_absent }}</h1>
                    </h6>
                </div>
            </div>
        </div>
    </div>
    <div>

        <div class="container">
    <div class="d-flex mt-4">
        <h3 class="fs-3 text-capitalize lead">Attendance List of {{ profile_username }}</h3>
    </div>
    <hr>
    <div class="row my-4 card shadow">
        <div class="col card-body">
            <table class="table table-striped" id="AttendanceListingTable">
                <thead>
                    <tr>
                        <th scope="col">Day</th>
                        <th scope="col">Name</th>
                        <th scope="col">Marked In</th>
                        <th scope="col">Marked Out</th>
                        <th scope="col">Status</th>
                    </tr>
                </thead>
                <tbody>

                    {% for obj in atte_obj.values %}
                     <tr>
                        <th scope="row">{{ obj.day }}</th>
                        <td>{{ name }}</td>
                        <td><b>{{ obj.marked_at }}</b></td>
                        <td><b>{{ obj.marked_out }}</b></td>
                        <td class="lead">{{ obj.status }}</td>
                    </tr>
                    {% empty %}
                    <tr class="mt-5">
                        <td colspan="7" align="center">
                            <p>No Attendance found</p>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <hr>
        </div>
    </div>
</div>

{% endblock %}


{% block scripts %}
<script>
        $(document).ready(function() {
                $('#AttendanceListingTable').DataTable();
        });
</script>
{% endblock %}

dashboard/templates/dashboard/dashboard.html
{% extends "main.html" %}
{% load static %}
{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-3">
        <div class="card" style="width: 18rem;">
          <img src="{% static 'img/markin.png' %}" class="card-img-top" alt="Mark My attendance" height="230">
            <div class="card-body text-center">
                <button id="mark-my-attd" class="btn btn-success">Mark My attendance</button>
  </div>
        </div>
        </div>
        <div class="col-3">
        <div class="card" style="width: 18rem;">
          <img src="{% static 'img/markout.jpg' %}" class="card-img-top" alt="Mark out attendance" height="230">
            <!-- Button trigger modal -->
            <div class="card-body text-center">
                <button id="mark-out-attd" type="button" class="btn btn-success">Mark out my attendance</button>
  </div>
        </div>
        </div>

        <div class="col-3">
      <div class="card" style="width: 18rem;">
          <img src="{% static 'img/attendance.jpg' %}" class="card-img-top" alt="records" height="230">
          <div class="card-body text-center">
            <a href="{% url 'dashboard:attendance-history' username=username %}" class="btn btn-success">Attendance History</a>
          </div>
      </div>
    </div>

        <div class="col-3">
      <div class="card" style="width: 18rem;">
          <img src="{% static 'img/upload.png' %}" class="card-img-top" alt="records" height="230">
          <div class="card-body text-center">
            <a href="{% url 'accounts:dataset' pk=userid.id %}" class="btn btn-success">Upload Dataset</a>
          </div>
      </div>
    </div>
    </div>
    <hr>
    {% if permission %}
    <div class="row mt-5 mb-5">
    <div class="col-3">
      <div class="card" style="width: 18rem;">
          <img src="{% static 'img/all_attendance.png' %}" class="card-img-top" alt="records" height="230">
          <div class="card-body text-center">
            <a href="{% url 'dashboard:all-attendance-history' %}" class="btn btn-success">All Attendance History</a>
          </div>
      </div>
    </div>

   <div class="col-3">
      <div class="card" style="width: 18rem;">
          <img src="{% static 'img/training3.jpg' %}" class="card-img-bottom" alt="Train Image Classifier" height="230">
          <div class="card-body text-center">
            <a href="{% url 'dashboard:training' %}" class="btn btn-success">Train Image Classifier</a>
          </div>
      </div>
    </div>
    </div>
    {% endif %}
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function() {
         $("#mark-my-attd").click(function() {
             document.getElementById('mark-my-attd').disabled=true;
             let url = "http://127.0.0.1:8000/markattendance/";
                fetch(url,  {
                    method : 'get',
                 }).then(response => response.json())
                 .then(data => {
                        document.getElementById('mark-my-attd').disabled=false;
                        if (data['status'] == 00) { alert('camera not found'); location.reload();  }
                        if (data['status'] == 10) { alert('Application has been closed'); location.reload();  }
                        if (data['status'] == 11) { alert(data['msg']); location.reload();  }
                 });
         });

         $("#mark-out-attd").click(function() {
            document.getElementById('mark-out-attd').disabled=true;
             let url = "http://127.0.0.1:8000/markoutattendance/";
                fetch(url,  {
                    method : 'get',
                 }).then(response => response.json())
                 .then(data => {
                        document.getElementById('mark-out-attd').disabled=false;
                        if (data['status'] == 00) { alert('camera not found'); location.reload();  }
                        if (data['status'] == 10) { alert('Application has been closed'); location.reload();  }
                        if (data['status'] == 11) { alert(data['msg']); location.reload();  }
                 });
         });

    });

</script>
{% endblock %}

dashboard/templates/dashboard/first_page.html
{% extends "main.html" %}
{% load static %}
{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-3">
        <div class="card" style="width: 18rem;">
          <img src="{% static 'img/markin.png' %}" class="card-img-top" alt="Mark My attendance" height="230">
            <!-- Button trigger modal -->
            <div class="card-body text-center">
                <button id="mark-my-attd" type="button" class="btn btn-success" >Mark my attendance</button>
  </div>
        </div>
        </div>

        <div class="col-3">
        <div class="card" style="width: 18rem;">
          <img src="{% static 'img/markout.jpg' %}" class="card-img-top" alt="Mark My attendance" height="230">
            <!-- Button trigger modal -->
            <div class="card-body text-center">
                <button id="mark-out-attd" type="button" class="btn btn-success">Mark out my attendance</button>
  </div>
        </div>
        </div>

    </div>
</div>

        <!-- Modal -->
<div class="modal fade" id="attendanceModal" tabindex="-1" aria-labelledby="attendanceModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="attendanceModalLabel">Enter email</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          {% csrf_token %}
        <input type="email" class="form-control" name="email" aria-describedby="emailHelp" required="" id="email">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" id="checkEmail" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}
{% block scripts %}
<script>
    $(document).ready(function() {
         $("#mark-my-attd").click(function() {
             document.getElementById('mark-my-attd').disabled=true;
             let url = "http://127.0.0.1:8000/markattendance/"
                fetch(url,  {
                    method : 'get',
                 }).then(response => response.json())
                 .then(data => {
                        document.getElementById('mark-my-attd').disabled=false;
                        if (data['status'] == 00) { alert('camera not found'); location.reload();  }
                        if (data['status'] == 10) { alert('Application has been closed'); location.reload();  }
                        if (data['status'] == 11) { alert(data['msg']); location.reload();  }
                 });
         });

         $("#mark-out-attd").click(function() {
             let url = "http://127.0.0.1:8000/markoutattendance/";
              document.getElementById('mark-out-attd').disabled=true;
                fetch(url,  {
                    method : 'get',
                 }).then(response => response.json())
                 .then(data => {
                         document.getElementById('mark-out-attd').disabled=false;
                        if (data['status'] == 00) { alert('camera not found'); location.reload();  }
                        if (data['status'] == 10) { alert('Application has been closed'); location.reload();  }
                        if (data['status'] == 11) { alert(data['msg']); location.reload();  }
                 });
         });

    });

</script>
{% endblock %}

dashboard/templates/dashboard/training.html
{% extends "main.html" %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <div class="row mb-5">

            <div class="col-6 justify-content-center text-center mt-5" style="">
        <div style="width: 18rem;margin-left:150px; margin-top:40px;">
       <img src="{% static 'img/training3.jpg' %}" class="img-responsive profile-pic card-img-top" alt="training">
                <hr>
            <form action="">
            {%  csrf_token %}
            <button type="button" class="btn btn-success" id="trainingImageBtn" data-bs-toggle="modal" data-bs-target="#trainingImage">
                Train Image Classifier
            </button>
                 </form>
        </div>
            </div>
            <div class="col-6 justify-content-right text-center mt-5" style="">
                    <img src="{% static 'graph/training.png' %}" alt=" " width="600" height="400">
                </div>
    </div>
    </div>

        <div class="modal fade" id="trainingImage" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Image Processing ..</h5>
      </div>
      <div class="modal-body text-center" id="processing_text">
            <div id="spinner" class="spinner-border" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
      </div>
      <div class="modal-footer">
        <button id="processingButton" type="button" class="btn btn-secondary d-none" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block scripts %}
        <script>
        $(document).ready(function() {
        $("#trainingImageBtn").click(function() {
                let url = "http://127.0.0.1:8000/training/all/";
                formData = new FormData();
                formData.append('csrfmiddlewaretoken',$('input[name=csrfmiddlewaretoken]').val());
                content = document.getElementById('processing_text');
                content.innerHTML = 'Please wait processing image';
                fetch(url,  {
                    method : 'post',
                    body: formData
                 }).then(response => response.json())
                 .then(data => {
                    content.innerHTML = " ";
                    content.innerHTML  = data['msg']
                    document.getElementById('processingButton').classList.remove('d-none');
                 });

                content = document.getElementById('processing_text');
        });
});
        </script>

{% endblock %}